/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dgD6tD4Ewxhqspb6sCy7BF

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsjgNpf40ESx3 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: JgNpf40ESx3-/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsjgNpf40ESx3
});
