/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dgD6tD4Ewxhqspb6sCy7BF

import * as React from "react";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: dgD6tD4Ewxhqspb6sCy7BF/projectModule
import { UserContext } from "../../../context/UserContext"; // plasmic-import: jiyl2fxkXbWu/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  userContextProps?: Partial<
    Omit<React.ComponentProps<typeof UserContext>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, userContextProps } = props;

  return <UserContext {...userContextProps}>{children}</UserContext>;
}
